### ISSUE TITLE
Test API: YAML-based datasets

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-jdbc#50]
It should be great to improve our dataset management. Doing it in Java is ok for simple things. In real applications with lots of relationships and join tables, we need something more compact... Like YAML. E.g.:

```yaml
jdbctest:
   datasets:
      ds1: 
         type: csv            # single table loaded from CSV
         table: my_table1
         csv: classpath:my1.csv
      ds2:
         type: inline_csv  # single table loaded from CSV
         table: my_table2
         header: c1,c2,c3
         values:
            - v1,v2,v3
            - v1,v2,v3
            - v1,v2,v3
      ds3: 
         type: group         # a combination of other datasources
         datasets:
            - ds1
            - ds2
```
