### ISSUE TITLE
Revisit the names and formats of Hikari health check configuration

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-jdbc#81]
Thinking of aligning Hikari health check configs with the newest format we are using on Jetty. The goal is to make names more descriptive and also support multiple thresholds. E.g.:
```yaml
# old
health:
  connectivityCheckTimeout: 250
  expected99thPercentile: 10
```

```yml
# new
health:
  connectivity:
    critical: 250ms
  connection99Percent:
    warning: 10ms
    critical: 500ms
```
